# Testing

# Background:

Bombay hospitality Ltd. operates a franchise model for producing exotic Norwegian dinners throughout New England. The operating cost for a franchise in a week (W) is given by the equation W = $1,000 + $5X, where X represents the number of units produced in a week. Recent feedback from restaurant owners suggests that this cost model may no longer be accurate, as their observed weekly operating costs are higher.

# Objective:
To investigate the restaurant owners' claim about the increase in weekly operating costs using hypothesis testing.

# Data Provided:

The theoretical weekly operating cost model: W = $1,000 + $5X

Sample of 25 restaurants with a mean weekly cost of Rs. 3,050

Number of units produced in a week (X) follows a normal distribution with a mean (μ) of 600 units and a standard deviation (σ) of 25 units


# Assignment Tasks::


# 1. State the Hypotheses statement:


In [2]:
# Null Hypothesis (H0): The mean weekly operating costs, as per the current cost model, have not increased.
H0 = "The mean weekly operating costs have not increased (μ = $4,000)"

# Alternative Hypothesis (H1): The mean weekly operating costs have increased compared to what the current cost model predicts.
H1 = "The mean weekly operating costs have increased (μ > $4,000)"

# 2. Calculate the Test Statistic:

Use the following formula to calculate the test statistic (t):

where:

ˉxˉ = sample mean weekly cost (Rs. 3,050)

μ = theoretical mean weekly cost according to the cost model (W = $1,000 + $5X for X = 600 units)

σ = 5*25 units

n = sample size (25 restaurants)


In [3]:
import math

# Given values
sample_mean = 3050
theoretical_mean = 4000
sample_std_dev = 5 * 25  # σ = 5*25 units
sample_size = 25

# Calculate the test statistic (t)
t = (sample_mean - theoretical_mean) / (sample_std_dev / math.sqrt(sample_size))
print("Test Statistic (t):", t)

Test Statistic (t): -38.0


# 3. Determine the Critical Value:

Using the alpha level of 5% (α = 0.05), determine the critical value from the standard normal (Z) distribution table.


In [4]:
# Given significance level (alpha)
alpha = 0.05

# Find the critical value from the standard normal (Z) distribution table
critical_value = 1.645  # for upper tail area of 0.05

print("Critical Value:", critical_value)

Critical Value: 1.645


# 4. Make a Decision:

# Compare the test statistic with the critical value to decide whether to reject the null hypothesis.


Since the absolute value of the test statistic (38.0) is far greater than the critical value (1.645), we reject the null hypothesis at the 5% significance level.

Rejecting the null hypothesis indicates that there is strong evidence to suggest that the mean weekly operating costs have increased significantly compared to what the current cost model predicts.

Therefore, based on the results of the hypothesis test, we conclude that there is a significant difference between the observed mean weekly operating costs and the theoretical mean predicted by the current cost model.

# 5. Conclusion:

Based on the decision in step 4, conclude whether there is strong evidence to support the restaurant owners' claim that the weekly operating costs are higher than the model suggests.


Based on the decision to reject the null hypothesis in step 4, there is indeed strong evidence to support the restaurant owners' claim that the weekly operating costs are higher than what the model suggests.

Therefore, the conclusion is that the observed mean weekly operating costs are significantly higher than what is predicted by the current cost model. This supports the restaurant owners' claim and suggests that adjustments to the cost model may be necessary to more accurately reflect the actual operating costs.